#!/bin/bash

#---------------------------------
# Using: 
# 
# ./build make filename.asm
# ./build clean
#---------------------------------

if [[ "$1" = "make" ]]
then
	avra -fI $2

else if [[ "$1" = "clean" ]]
then
	rm *.hex *.obj *.cof

fi

fi
